main: Python_Invoker.cpp
	g++ Python_Invoker.cpp -o main -I /usr/include/python3.8/ -l python3.8 -I /home/acs/anaconda3/envs/python36/lib/python3.6/site-packages/numpy/core/include/ -I /home/acs/anaconda3/lib/python3.7/site-packages/
clean:
	rm main
